import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Order } from '../types';

const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
}

const buildReceiptDoc = (order: Order, generatedByUsername: string): jsPDF => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Insophinia Manufacturing Pvt Ltd', 14, 22);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('123 Industrial Way, Metropolis, 12345', 14, 30);
    
    doc.setFontSize(18);
    doc.text('INVOICE / RECEIPT', 150, 22);

    // Order Details
    doc.setLineWidth(0.5);
    doc.line(14, 35, 200, 35);

    doc.setFontSize(10);
    doc.text(`Order ID: ${order.id}`, 14, 42);
    doc.text(`Date: ${new Date(order.createdAt).toLocaleString()}`, 14, 48);
    doc.text(`Customer: ${order.customerName || 'N/A'}`, 14, 54);
    doc.text(`Contact: ${order.customerContact || 'N/A'}`, 14, 60);
    doc.text(`Delivery Address:`, 14, 66);
    doc.text(order.customerAddress || 'Pickup / Not applicable', 14, 72, { maxWidth: 120 });
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Status:`, 150, 42);
    doc.setFont('helvetica', 'normal');
    doc.text(order.status, 165, 42);

    // Table
    // FIX: Correctly access properties on the 'OrderItem' type.
    const tableData = order.items.map(item => [
        item.sku,
        item.name,
        item.quantity,
        formatCurrency(item.price_at_purchase),
        // NOTE: Warranty info is not available on OrderItem, defaulting to 0.
        `${0} months`,
        formatCurrency(item.price_at_purchase * item.quantity)
    ]);

    autoTable(doc, {
        startY: 85,
        head: [['SKU', 'Item Description', 'Qty', 'Unit Price', 'Warranty', 'Total']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: '#0D47A1' }
    });

    // Totals Section
    const finalY = (doc as any).lastAutoTable.finalY;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Subtotal:', 140, finalY + 10);
    doc.setFont('helvetica', 'normal');
    doc.text(formatCurrency(order.subtotal), 170, finalY + 10);
    
    if (order.discountAmount > 0) {
        doc.setFont('helvetica', 'bold');
        // FIX: The `discountApplied` property does not exist on the Order type.
        // The type of discount (percentage or fixed) is not available here.
        const discountText = 'Total Discount:';
        doc.text(discountText, 168, finalY + 16, { align: 'right' });
        doc.setFont('helvetica', 'normal');
        doc.text(`-${formatCurrency(order.discountAmount)}`, 170, finalY + 16);
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL:', 140, finalY + 24);
    doc.text(formatCurrency(order.total), 170, finalY + 24);
    
    // Signature and generation info
    const signatureY = Math.max(finalY + 50, 250);
    doc.setLineWidth(0.2);
    doc.line(14, signatureY, 80, signatureY);
    doc.setFontSize(10);
    doc.text('Authorized Signature', 14, signatureY + 5);

    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(`Generated by: ${generatedByUsername}`, 140, signatureY - 5);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 140, signatureY);

    // Footer
    doc.setLineWidth(0.5);
    doc.line(14, 280, 200, 280);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Thank you for your business! This is an automated system-generated receipt.', 14, 285);

    return doc;
}


export const generateReceipt = (order: Order, generatedByUsername: string) => {
    const doc = buildReceiptDoc(order, generatedByUsername);
    doc.save(`receipt-order-${order.id}.pdf`);
};

export const generateReceiptDataUri = (order: Order, generatedByUsername: string): string => {
    const doc = buildReceiptDoc(order, generatedByUsername);
    return doc.output('datauristring');
};